"""
Bank DDoS Detection System - Alert Model

Stores security alerts generated when high risk or DDoS traffic is detected by the ML classifier.
Supported statuses: NEW, ACKNOWLEDGED, RESOLVED.
"""

from datetime import datetime, timezone
from extensions import db


class Alert(db.Model):
    """
    SQLAlchemy Model for the 'alerts' table.
    Captures actionable DDoS alerts generated by the ML pipeline.
    """
    __tablename__ = 'alerts'

    VALID_STATUSES = ("NEW", "ACKNOWLEDGED", "RESOLVED")

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    timestamp = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), nullable=False, index=True)
    alert_type = db.Column(db.String(50), nullable=False, default="DDoS")
    risk_level = db.Column(db.String(20), nullable=False, default="HIGH", index=True)
    message = db.Column(db.Text, nullable=False)
    source_ip = db.Column(db.String(45), nullable=True, index=True)
    destination_ip = db.Column(db.String(45), nullable=True, index=True)
    status = db.Column(db.String(20), nullable=False, default="NEW", index=True)

    def to_dict(self):
        """Serializes the Alert model instance into a dictionary."""
        return {
            "id": self.id,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "alert_type": self.alert_type,
            "risk_level": self.risk_level,
            "message": self.message,
            "source_ip": self.source_ip,
            "destination_ip": self.destination_ip,
            "status": self.status
        }

    def __repr__(self):
        return f"<Alert id={self.id} type={self.alert_type} risk={self.risk_level} status={self.status}>"
